[package]
name = "http_data"
version = "0.11.0"
description = "Traits for retrieving http data"
repository = "https://github.com/estk/http_data"
license = "MIT"
edition = "2024"

[dependencies]
bytes = "1.11.0"
enumflags2 = "0.7.12"
http = "1.4.0"
http-body = "1.0.1"
http-body-util = "0.1.3"
